"""initiating google table

Revision ID: 943b4653ce16
Revises: 
Create Date: 2023-02-03 14:48:25.828890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943b4653ce16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_merchandise',
    sa.Column('categories', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('timedate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_merchandise')
    # ### end Alembic commands ###
